### ISSUE TITLE
Screenshot protection

### ISSUE THREAD

**Issue by Zahlentheorie** [surespot/surespot-ios#22]
When closing surespot a background screenshot is taken for the app switcher. After that it's possible to read the messages without opening surespot. Can you implement a screenshot protection function?

**Comment by jacklibonnie** [comment]
i download this project,and add google-api-objectivec and cryptopp-5.6.2-ios,but i stuck in compile because of compile errors,can you help me?

**Comment by wp9015362** [comment]
+1

Also it seems like as if you can take normal screenshots inside surespot-iOS as well.

In surespot-Android taking screenshots inside the app is prohibited/disabled.

Could you please prohibit/disable it in surespot-iOS as well?

**Comment by 2fours** [comment]
App switcher image will be fixed in the next version. iOS does not allow us to prevent screenshots.

**Comment by 2fours** [comment]
App switcher protection implemented in v10.
