### ISSUE TITLE
Japanese keyboard overlaps the input box

### ISSUE THREAD

**Issue by juhovii** [surespot/surespot-ios#7]
The Japanese keyboard overlaps (both alphabet and kana based keyboards) the message input box on both the iPhone and iPad. The Japanese input method has an extra row above with suggestions and predictive text which is the problem.

On the iPad it doesn't overlap if Japanese input is already selected when entering a chat. If you enter the chat with English as the selected input method and then change into Japanese - the input box gets overlapped again.

On the iPhone the keyboard overlaps the input area always. Changing inputs types during the chat doesn't affect at all.

**Comment by 2fours** [comment]
Should be fixed in v9.
